import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Script from "next/script"; // Import Script correctly
import { ThemeProvider } from "@/components/theme-provider.";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", // Fixed the typo
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const router = useRouter();

  // Check if the current route matches /trip/[id]

  return (
    <html lang="en">

      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer/>
        </ThemeProvider>

        <Script
        id="chatbot-config"
          dangerouslySetInnerHTML={{
            __html: `
        window.userChatbotConfig = {
            chaticon: {
                position: 'right',
                icon_color: 'black',
                icon_background_color: '#F2E8C6'
            },
            chatbotWindow: {
                headerBackgroundColor: '#F2E8C6',
                headerTextColor: 'black',
                bodyBackgroundColor: 'white',
                bodyTextColor: 'black',
                logo: '/images/dubai.jpg'
            },
            personaId: "85d562d5-b317-45a5-af2e-9d6bc0d07051",
            privateKey: 'OTY1YTU2MzA2MmUzNDcyOWJkMzY3ZDA4ZjIyNTZiNDg='
        }
            `,
          }}
        />
        
      </body>
    </html>
  );
}
